
set(cryptopp_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR})

set(cryptopp_HEADERS
${cryptopp_SOURCES_DIR}/3way.h
${cryptopp_SOURCES_DIR}/adler32.h
${cryptopp_SOURCES_DIR}/aes.h
${cryptopp_SOURCES_DIR}/algebra.h
${cryptopp_SOURCES_DIR}/algparam.h
${cryptopp_SOURCES_DIR}/arc4.h
${cryptopp_SOURCES_DIR}/argnames.h
${cryptopp_SOURCES_DIR}/asn.h
${cryptopp_SOURCES_DIR}/authenc.h
${cryptopp_SOURCES_DIR}/base32.h
${cryptopp_SOURCES_DIR}/base64.h
${cryptopp_SOURCES_DIR}/basecode.h
${cryptopp_SOURCES_DIR}/bench.h
${cryptopp_SOURCES_DIR}/blake2.h
${cryptopp_SOURCES_DIR}/blowfish.h
${cryptopp_SOURCES_DIR}/blumshub.h
${cryptopp_SOURCES_DIR}/camellia.h
${cryptopp_SOURCES_DIR}/cast.h
${cryptopp_SOURCES_DIR}/cbcmac.h
${cryptopp_SOURCES_DIR}/ccm.h
${cryptopp_SOURCES_DIR}/chacha.h
${cryptopp_SOURCES_DIR}/channels.h
${cryptopp_SOURCES_DIR}/cmac.h
${cryptopp_SOURCES_DIR}/config.h
${cryptopp_SOURCES_DIR}/cpu.h
${cryptopp_SOURCES_DIR}/crc.h
${cryptopp_SOURCES_DIR}/cryptlib.h
${cryptopp_SOURCES_DIR}/default.h
${cryptopp_SOURCES_DIR}/des.h
${cryptopp_SOURCES_DIR}/dh2.h
${cryptopp_SOURCES_DIR}/dh.h
${cryptopp_SOURCES_DIR}/dll.h
${cryptopp_SOURCES_DIR}/dmac.h
${cryptopp_SOURCES_DIR}/dsa.h
${cryptopp_SOURCES_DIR}/eax.h
${cryptopp_SOURCES_DIR}/ec2n.h
${cryptopp_SOURCES_DIR}/eccrypto.h
${cryptopp_SOURCES_DIR}/ecp.h
${cryptopp_SOURCES_DIR}/elgamal.h
${cryptopp_SOURCES_DIR}/emsa2.h
${cryptopp_SOURCES_DIR}/eprecomp.h
${cryptopp_SOURCES_DIR}/esign.h
${cryptopp_SOURCES_DIR}/factory.h
${cryptopp_SOURCES_DIR}/fhmqv.h
${cryptopp_SOURCES_DIR}/files.h
${cryptopp_SOURCES_DIR}/filters.h
${cryptopp_SOURCES_DIR}/fips140.h
${cryptopp_SOURCES_DIR}/fltrimpl.h
${cryptopp_SOURCES_DIR}/gcm.h
${cryptopp_SOURCES_DIR}/gf2_32.h
${cryptopp_SOURCES_DIR}/gf256.h
${cryptopp_SOURCES_DIR}/gf2n.h
${cryptopp_SOURCES_DIR}/gfpcrypt.h
${cryptopp_SOURCES_DIR}/gost.h
${cryptopp_SOURCES_DIR}/gzip.h
${cryptopp_SOURCES_DIR}/hex.h
${cryptopp_SOURCES_DIR}/hkdf.h
${cryptopp_SOURCES_DIR}/hmac.h
${cryptopp_SOURCES_DIR}/hmqv.h
${cryptopp_SOURCES_DIR}/hrtimer.h
${cryptopp_SOURCES_DIR}/ida.h
${cryptopp_SOURCES_DIR}/idea.h
${cryptopp_SOURCES_DIR}/integer.h
${cryptopp_SOURCES_DIR}/iterhash.h
${cryptopp_SOURCES_DIR}/keccak.h
${cryptopp_SOURCES_DIR}/lubyrack.h
${cryptopp_SOURCES_DIR}/luc.h
${cryptopp_SOURCES_DIR}/mars.h
${cryptopp_SOURCES_DIR}/md2.h
${cryptopp_SOURCES_DIR}/md4.h
${cryptopp_SOURCES_DIR}/md5.h
${cryptopp_SOURCES_DIR}/mdc.h
${cryptopp_SOURCES_DIR}/mersenne.h
${cryptopp_SOURCES_DIR}/misc.h
${cryptopp_SOURCES_DIR}/modarith.h
${cryptopp_SOURCES_DIR}/modes.h
${cryptopp_SOURCES_DIR}/modexppc.h
${cryptopp_SOURCES_DIR}/mqueue.h
${cryptopp_SOURCES_DIR}/mqv.h
${cryptopp_SOURCES_DIR}/nbtheory.h
${cryptopp_SOURCES_DIR}/network.h
${cryptopp_SOURCES_DIR}/nr.h
${cryptopp_SOURCES_DIR}/oaep.h
${cryptopp_SOURCES_DIR}/oids.h
${cryptopp_SOURCES_DIR}/osrng.h
${cryptopp_SOURCES_DIR}/ossig.h
${cryptopp_SOURCES_DIR}/panama.h
${cryptopp_SOURCES_DIR}/pch.h
${cryptopp_SOURCES_DIR}/pkcspad.h
${cryptopp_SOURCES_DIR}/polynomi.h
${cryptopp_SOURCES_DIR}/pssr.h
${cryptopp_SOURCES_DIR}/pubkey.h
${cryptopp_SOURCES_DIR}/pwdbased.h
${cryptopp_SOURCES_DIR}/queue.h
${cryptopp_SOURCES_DIR}/rabin.h
${cryptopp_SOURCES_DIR}/randpool.h
${cryptopp_SOURCES_DIR}/rc2.h
${cryptopp_SOURCES_DIR}/rc5.h
${cryptopp_SOURCES_DIR}/rc6.h
${cryptopp_SOURCES_DIR}/rdrand.h
${cryptopp_SOURCES_DIR}/resource.h
${cryptopp_SOURCES_DIR}/rijndael.h
${cryptopp_SOURCES_DIR}/ripemd.h
${cryptopp_SOURCES_DIR}/rng.h
${cryptopp_SOURCES_DIR}/rsa.h
${cryptopp_SOURCES_DIR}/rw.h
${cryptopp_SOURCES_DIR}/safer.h
${cryptopp_SOURCES_DIR}/salsa.h
${cryptopp_SOURCES_DIR}/seal.h
${cryptopp_SOURCES_DIR}/secblock.h
${cryptopp_SOURCES_DIR}/seckey.h
${cryptopp_SOURCES_DIR}/seed.h
${cryptopp_SOURCES_DIR}/serpent.h
${cryptopp_SOURCES_DIR}/serpentp.h
${cryptopp_SOURCES_DIR}/sha3.h
${cryptopp_SOURCES_DIR}/shacal2.h
${cryptopp_SOURCES_DIR}/sha.h
${cryptopp_SOURCES_DIR}/shark.h
${cryptopp_SOURCES_DIR}/simple.h
${cryptopp_SOURCES_DIR}/skipjack.h
${cryptopp_SOURCES_DIR}/smartptr.h
${cryptopp_SOURCES_DIR}/socketft.h
${cryptopp_SOURCES_DIR}/sosemanuk.h
${cryptopp_SOURCES_DIR}/square.h
${cryptopp_SOURCES_DIR}/stdcpp.h
${cryptopp_SOURCES_DIR}/strciphr.h
${cryptopp_SOURCES_DIR}/tea.h
${cryptopp_SOURCES_DIR}/tiger.h
${cryptopp_SOURCES_DIR}/trap.h
${cryptopp_SOURCES_DIR}/trdlocal.h
${cryptopp_SOURCES_DIR}/trunhash.h
${cryptopp_SOURCES_DIR}/ttmac.h
${cryptopp_SOURCES_DIR}/twofish.h
${cryptopp_SOURCES_DIR}/validate.h
${cryptopp_SOURCES_DIR}/vmac.h
${cryptopp_SOURCES_DIR}/wait.h
${cryptopp_SOURCES_DIR}/wake.h
${cryptopp_SOURCES_DIR}/whrlpool.h
${cryptopp_SOURCES_DIR}/winpipes.h
${cryptopp_SOURCES_DIR}/words.h
${cryptopp_SOURCES_DIR}/xtrcrypt.h
${cryptopp_SOURCES_DIR}/xtr.h
${cryptopp_SOURCES_DIR}/zdeflate.h
${cryptopp_SOURCES_DIR}/zinflate.h
${cryptopp_SOURCES_DIR}/zlib.h)


set(cryptopp_SOURCES
${cryptopp_SOURCES_DIR}/3way.cpp
${cryptopp_SOURCES_DIR}/adler32.cpp
${cryptopp_SOURCES_DIR}/algebra.cpp
${cryptopp_SOURCES_DIR}/algparam.cpp
${cryptopp_SOURCES_DIR}/arc4.cpp
${cryptopp_SOURCES_DIR}/asn.cpp
${cryptopp_SOURCES_DIR}/authenc.cpp
${cryptopp_SOURCES_DIR}/base32.cpp
${cryptopp_SOURCES_DIR}/base64.cpp
${cryptopp_SOURCES_DIR}/basecode.cpp
${cryptopp_SOURCES_DIR}/bench1.cpp
${cryptopp_SOURCES_DIR}/bench2.cpp
${cryptopp_SOURCES_DIR}/bfinit.cpp
${cryptopp_SOURCES_DIR}/blake2.cpp
${cryptopp_SOURCES_DIR}/blowfish.cpp
${cryptopp_SOURCES_DIR}/blumshub.cpp
${cryptopp_SOURCES_DIR}/camellia.cpp
${cryptopp_SOURCES_DIR}/cast.cpp
${cryptopp_SOURCES_DIR}/casts.cpp
${cryptopp_SOURCES_DIR}/cbcmac.cpp
${cryptopp_SOURCES_DIR}/ccm.cpp
${cryptopp_SOURCES_DIR}/chacha.cpp
${cryptopp_SOURCES_DIR}/channels.cpp
${cryptopp_SOURCES_DIR}/cmac.cpp
${cryptopp_SOURCES_DIR}/cpu.cpp
${cryptopp_SOURCES_DIR}/crc.cpp
${cryptopp_SOURCES_DIR}/cryptlib.cpp
${cryptopp_SOURCES_DIR}/datatest.cpp
${cryptopp_SOURCES_DIR}/default.cpp
${cryptopp_SOURCES_DIR}/des.cpp
${cryptopp_SOURCES_DIR}/dessp.cpp
${cryptopp_SOURCES_DIR}/dh2.cpp
${cryptopp_SOURCES_DIR}/dh.cpp
${cryptopp_SOURCES_DIR}/dll.cpp
${cryptopp_SOURCES_DIR}/dlltest.cpp
${cryptopp_SOURCES_DIR}/dsa.cpp
${cryptopp_SOURCES_DIR}/eax.cpp
${cryptopp_SOURCES_DIR}/ec2n.cpp
${cryptopp_SOURCES_DIR}/eccrypto.cpp
${cryptopp_SOURCES_DIR}/ecp.cpp
${cryptopp_SOURCES_DIR}/elgamal.cpp
${cryptopp_SOURCES_DIR}/emsa2.cpp
${cryptopp_SOURCES_DIR}/eprecomp.cpp
${cryptopp_SOURCES_DIR}/esign.cpp
${cryptopp_SOURCES_DIR}/files.cpp
${cryptopp_SOURCES_DIR}/filters.cpp
${cryptopp_SOURCES_DIR}/fips140.cpp
${cryptopp_SOURCES_DIR}/fipsalgt.cpp
${cryptopp_SOURCES_DIR}/fipstest.cpp
${cryptopp_SOURCES_DIR}/gcm.cpp
${cryptopp_SOURCES_DIR}/gf2_32.cpp
${cryptopp_SOURCES_DIR}/gf256.cpp
${cryptopp_SOURCES_DIR}/gf2n.cpp
${cryptopp_SOURCES_DIR}/gfpcrypt.cpp
${cryptopp_SOURCES_DIR}/gost.cpp
${cryptopp_SOURCES_DIR}/gzip.cpp
${cryptopp_SOURCES_DIR}/hex.cpp
${cryptopp_SOURCES_DIR}/hmac.cpp
${cryptopp_SOURCES_DIR}/hrtimer.cpp
${cryptopp_SOURCES_DIR}/ida.cpp
${cryptopp_SOURCES_DIR}/idea.cpp
${cryptopp_SOURCES_DIR}/integer.cpp
${cryptopp_SOURCES_DIR}/iterhash.cpp
${cryptopp_SOURCES_DIR}/keccak.cpp
${cryptopp_SOURCES_DIR}/luc.cpp
${cryptopp_SOURCES_DIR}/mars.cpp
${cryptopp_SOURCES_DIR}/marss.cpp
${cryptopp_SOURCES_DIR}/md2.cpp
${cryptopp_SOURCES_DIR}/md4.cpp
${cryptopp_SOURCES_DIR}/md5.cpp
${cryptopp_SOURCES_DIR}/misc.cpp
${cryptopp_SOURCES_DIR}/modes.cpp
${cryptopp_SOURCES_DIR}/mqueue.cpp
${cryptopp_SOURCES_DIR}/mqv.cpp
${cryptopp_SOURCES_DIR}/nbtheory.cpp
${cryptopp_SOURCES_DIR}/network.cpp
${cryptopp_SOURCES_DIR}/oaep.cpp
${cryptopp_SOURCES_DIR}/osrng.cpp
${cryptopp_SOURCES_DIR}/panama.cpp
${cryptopp_SOURCES_DIR}/pch.cpp
${cryptopp_SOURCES_DIR}/pkcspad.cpp
${cryptopp_SOURCES_DIR}/polynomi.cpp
${cryptopp_SOURCES_DIR}/pssr.cpp
${cryptopp_SOURCES_DIR}/pubkey.cpp
${cryptopp_SOURCES_DIR}/queue.cpp
${cryptopp_SOURCES_DIR}/rabin.cpp
${cryptopp_SOURCES_DIR}/randpool.cpp
${cryptopp_SOURCES_DIR}/rc2.cpp
${cryptopp_SOURCES_DIR}/rc5.cpp
${cryptopp_SOURCES_DIR}/rc6.cpp
${cryptopp_SOURCES_DIR}/rdrand.cpp
${cryptopp_SOURCES_DIR}/rdtables.cpp
${cryptopp_SOURCES_DIR}/regtest.cpp
${cryptopp_SOURCES_DIR}/rijndael.cpp
${cryptopp_SOURCES_DIR}/ripemd.cpp
${cryptopp_SOURCES_DIR}/rng.cpp
${cryptopp_SOURCES_DIR}/rsa.cpp
${cryptopp_SOURCES_DIR}/rw.cpp
${cryptopp_SOURCES_DIR}/safer.cpp
${cryptopp_SOURCES_DIR}/salsa.cpp
${cryptopp_SOURCES_DIR}/seal.cpp
${cryptopp_SOURCES_DIR}/seed.cpp
${cryptopp_SOURCES_DIR}/serpent.cpp
${cryptopp_SOURCES_DIR}/sha3.cpp
${cryptopp_SOURCES_DIR}/shacal2.cpp
${cryptopp_SOURCES_DIR}/sha.cpp
${cryptopp_SOURCES_DIR}/sharkbox.cpp
${cryptopp_SOURCES_DIR}/shark.cpp
${cryptopp_SOURCES_DIR}/simple.cpp
${cryptopp_SOURCES_DIR}/skipjack.cpp
${cryptopp_SOURCES_DIR}/socketft.cpp
${cryptopp_SOURCES_DIR}/sosemanuk.cpp
${cryptopp_SOURCES_DIR}/square.cpp
${cryptopp_SOURCES_DIR}/squaretb.cpp
${cryptopp_SOURCES_DIR}/strciphr.cpp
${cryptopp_SOURCES_DIR}/tea.cpp
${cryptopp_SOURCES_DIR}/test.cpp
${cryptopp_SOURCES_DIR}/tftables.cpp
${cryptopp_SOURCES_DIR}/tiger.cpp
${cryptopp_SOURCES_DIR}/tigertab.cpp
${cryptopp_SOURCES_DIR}/trdlocal.cpp
${cryptopp_SOURCES_DIR}/ttmac.cpp
${cryptopp_SOURCES_DIR}/twofish.cpp
${cryptopp_SOURCES_DIR}/validat1.cpp
${cryptopp_SOURCES_DIR}/validat2.cpp
${cryptopp_SOURCES_DIR}/validat3.cpp
${cryptopp_SOURCES_DIR}/vmac.cpp
${cryptopp_SOURCES_DIR}/wait.cpp
${cryptopp_SOURCES_DIR}/wake.cpp
${cryptopp_SOURCES_DIR}/whrlpool.cpp
${cryptopp_SOURCES_DIR}/winpipes.cpp
${cryptopp_SOURCES_DIR}/xtr.cpp
${cryptopp_SOURCES_DIR}/xtrcrypt.cpp
${cryptopp_SOURCES_DIR}/zdeflate.cpp
${cryptopp_SOURCES_DIR}/zinflate.cpp
${cryptopp_SOURCES_DIR}/zlib.cpp    
${EXT_SOURCES})
